version: 0.2

env:
  secrets-manager:
    ARTIFACTORY_PASSWORD: "artifactory_password"
phases:
  pre_build:
    commands:
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/v0.19.1/install.sh | sh -s -- -b /usr/local/bin v0.19.1
      - curl -sSfL https://raw.githubusercontent.com/anchore/grype/v0.15.0/install.sh | sh -s -- -b /usr/local/bin v0.15.0
      - echo Logging in to Artifactory...
      - echo $ARTIFACTORY_PASSWORD | docker login --username ci --password-stdin tintulip.jfrog.io
      - echo -n ci > artiUsername.txt
      - echo -n $ARTIFACTORY_PASSWORD > artiPassword.txt
  build:
    commands:
      - echo Build started on `date`
      - docker run --rm -v "$CODEBUILD_SRC_DIR:/src" -v "$CODEBUILD_SRC_DIR_policies/semgrep-rules/java:/policies" tintulip.jfrog.io/docker-remote/returntocorp/semgrep -c="p/java" -c="/policies" /src --error
      - echo "Building the Docker image"
      - DOCKER_BUILDKIT=1 docker build -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION --secret id=artiUsername,src=artiUsername.txt --secret id=artiPassword,src=artiPassword.txt .
      - rm artiUsername.txt artiPassword.txt
      - syft $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION -o json | grype --fail-on high
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
