version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Pre_build App"
  build:
    commands:
      - java -version
      - ./gradlew clean test bootJar
  post_build:
    commands:
      - echo "post_build App"