version: 0.2

phases:
  install:
    commands:
      - echo "Install Infra"
  pre_build:
    commands:
      - echo "Pre_build Infra"
  build:
    commands:
      - echo "build Infra"
  post_build:
    commands:
      - echo "post_build Infra"