version: 0.2

phases:
  install:
    commands:
      - wget -nv https://releases.hashicorp.com/terraform/0.15.4/terraform_0.15.4_linux_amd64.zip
      - unzip terraform_0.15.4_linux_amd64.zip
      # FIXME: add shasum check for tf binary!!
  pre_build:
    commands:
      - ./terraform -chdir=environments/preproduction init
  build:
    commands:
      - ./terraform -chdir=environments/preproduction plan -no-color -out=preproduction.tfplan
      - ./terraform -chdir=environments/preproduction show -no-color -out=preproduction.tfplan
      - ./terraform -chdir=environments/preproduction apply -no-color -auto-approve -input=false preproduction.tfplan
  post_build:
    commands:
      - echo "done"
